# Generated by Django 4.2 on 2023-04-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=512)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictedResult',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.PositiveBigIntegerField()),
                ('gender', models.PositiveBigIntegerField()),
                ('county', models.CharField(max_length=100)),
                ('maritalStatus', models.PositiveBigIntegerField()),
                ('coupleDiscordant', models.PositiveBigIntegerField()),
                ('SexWithWoman', models.CharField(max_length=256)),
                ('SexWithMan', models.CharField(max_length=256)),
                ('condom_use', models.CharField(max_length=256)),
                ('sw', models.PositiveBigIntegerField()),
                ('pwid', models.PositiveBigIntegerField()),
                ('testedBefore', models.PositiveBigIntegerField()),
                ('presumedTB', models.PositiveBigIntegerField()),
                ('treatmentTB', models.PositiveBigIntegerField()),
                ('sti', models.CharField(max_length=100)),
                ('rapevictim', models.CharField(max_length=100)),
                ('HIVPrEP', models.CharField(max_length=100)),
                ('y_pred', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='resultMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('result', models.CharField(max_length=256)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
